### ISSUE TITLE
Check fails to resolve commits in forks

### ISSUE THREAD

**Issue by Bckempa** [space-ros/check-commit-message-action#3]
BTW, @EzraBrooks I can see that the commit message CI checker failed. I believe its because I opened pull request from my own repo. I think this CI check should be fixed, wdyt? All the PRs that were merged after adding this check were opened from `space-ros/docker` repo, and I believe that is why CI was green for them.

_Originally posted by @xfiderek in https://github.com/space-ros/docker/issues/152#issuecomment-2387755288_

**Comment by Bckempa** [comment]
Sticking @EzraBrooks with this (feel free to delegate 😉) since he was the original author.

**Comment by eholum** [comment]
Volun-delegated to me, should be fixed (possibly in a silly, silly way) by https://github.com/space-ros/check-commit-message-action/pull/4
